language: R
cache: packages
sudo: false

r:
  - oldrel
  - release
  - devel

before_deploy:
  - R -e "install.packages('roxygen2', repos = 'http://cran.rstudio.com')"
  - R -e "staticdocs::build_site(examples = TRUE)"

after_success:
  - Rscript -e 'covr::codecov()'
